[build]
  functions = ".netlify/functions"

[functions]
  # Use Node.js 18 for native fetch support
  node_bundler = "esbuild"

[[redirects]]
  # This ensures function routes work properly
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

